CREATE TABLE `SEARCH_QUERY` (
      `QUERY_HASH` bigint(20) NOT NULL,
      `TIME_PERSIST` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (`QUERY_HASH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

